enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1
cli-version = "dev"
patches-version = "dev"
patches-source = "rushiforai/mirror"
# patches-version = "v5.51.0-dev.2"
# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
app-name = "YouTube"
arch = "arm64-v8a" 
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """

# [YouTube-Morphe]
# app-name = "YouTube"
# arch = "arm64-v8a" 
# build-mode = "apk"
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "Morphe"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
app-name = "Music"
arch = "arm64-v8a" 
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """

# [Music-Morphe]
# app-name = "Music"
# arch = "arm64-v8a" 
# build-mode = "apk"
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "Morphe"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Reddit]
app-name = "Reddit"
arch = "arm64-v8a" 
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
    
[Instagram]
app-name = "Instagram"
arch = "arm64-v8a" 
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram/"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
    

# [Reddit-Morphe]
# app-name = "Reddit"
# rv-brand = "Morphe"
# arch = "arm64-v8a" 
# build-mode = "apk"
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[GooglePhotos]
arch = "arm64-v8a" 
build-mode = "apk"
#apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
included-patches = """\
    'Enable DCIM folders backup control' 'Remove screenshot restriction' 'Remove screen capture restriction' \
    """

[Spotify]
arch = "arm64-v8a" 
build-mode = "apk"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
