enable-magisk-update = false # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Facebook]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' \
    """
uptodown-dlurl = "https://facebook.en.uptodown.com/android"
version = "auto"

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Enable DCIM folders backup control' 'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
version = "auto"

[Messenger]
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction'\
    """
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Music-Anddea]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
app-name = "Music"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
patches-source = "anddea/revanced-patches"
rv-brand = "Anddea Extended"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
#cli-source = "inotia00/revanced-cli"

[Music-Extended]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
app-name = "Music"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
#cli-source = "inotia00/revanced-cli"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "auto"

[Reddit-Anddea]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
app-name = "Reddit"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced Anddea"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "auto"
#cli-source = "inotia00/revanced-cli"

[Reddit-Extended]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
app-name = "Reddit"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
version = "auto"
#cli-source = "inotia00/revanced-cli"

[Spotify]
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "auto"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

[TikTok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
build-mode = "apk"
included-patches = """\
    'SIM spoof' 'Remove screenshot restriction' \
    """
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
#arch = "arm64-v8a"
#version = "auto"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
#dpi = "120-640dpi"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
version = "auto"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-Anddea]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
patches-source = "anddea/revanced-patches"
rv-brand = "ReVanced Anddea"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
#cli-source = "inotia00/revanced-cli"

[YouTube-Extended]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
app-name = "YouTube"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = """\
    'Remove screenshot restriction' 'Remove screen capture restriction' \
    """
patches-source = "inotia00/revanced-patches"
rv-brand = "ReVanced Extended"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
#archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
#cli-source = "inotia00/revanced-cli"
